# This workflow for cleaning up version
name: delete version

# invoke manually
  on:
    workflow_dispatch:
      inputs:
        version:
          description: 'Version to delete'
          required: true

  jobs:
    build_maven_job:
      name: Code Checkout and Maven
      runs-on: ubuntu-latest