# This workflow for cleaning up version as per request
name: Delete Version

# invoke manually
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to delete'
        required: true

jobs:
  build_maven_job:
    name: Code Checkout and Maven
    runs-on: ubuntu-latest

    steps:
      - name: Show Info
        run: |
          echo ${{github.event.inputs.version}}

      - name: curl
        run: |
          echo "PACKAGE_VERSION_ID=$(echo $(jq -r '.data.repository.packages.nodes[0].version.id'  <<< $(curl -sL -X POST https://api.github.com/graphql \
          -H "Authorization: bearer ${{secrets.ACCESS_PAT}}" \
          -d '{"query":"query{repository(owner:\"ansg86\",name:\"reactivedb\"){packages(first:1){nodes{version(version:\"0.0.1\"){id,version}}}}}"}' | jq .)))" >> $GITHUB_ENV

      - name: get version id
        run: |
          echo $PACKAGE_VERSION_ID

#      - name: perform deletion
#        uses: actions/delete-package-versions@v1
#        with:
#          package-version-ids: 'PV_lADOGPYwsc4AEArPzgDJZfI'
#          token: ${{secrets.ACCESS_PAT}}