# This workflow for cleaning up version as per request
name: Delete Version

# invoke manually
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to delete'
        required: true

jobs:
  build_maven_job:
    name: Code Checkout and Maven
    runs-on: ubuntu-latest

    steps:
      - name: Show Info
        run: |
          echo ${{github.event.inputs.version}}

      - name: perform deletion
        uses: actions/delete-package-versions@v1
        with:
          package-version-ids: 'PV_lADOGPYwsc4AEArPzgDJZfI'
          token: {{ secrets.ACCESS_PAT }}